export const SET_SINGER_CATEGORY = 'SET_SINGER_CATEGORY'

export const SET_SINGER_INFO = 'SET_SINGER_INFO'

export const SET_MUSIC_LIST = 'SET_MUSIC_LIST'

export const SET_PLAY_LIST = 'SET_PLAY_LIST'

export const SET_RANK_LIST = 'SET_RANK_LIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_PLAYING_MODE = 'SET_PLAYING_MODE'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'

export const SET_PLAY_HISTORY = 'SET_PLAY_HISTORY'

export const SET_FAVOURATE_LIST = 'SET_FAVOURATE_LIST'
