export const SET_MUSIC_LIST = 'SET_MUSIC_LIST'

export const SET_PLAY_LIST = 'SET_PLAY_LIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'
